### ISSUE TITLE
Does old SDK still exist?

### ISSUE THREAD

**Issue by joeldenning** [amzn/amazon-pay-api-sdk-nodejs#6]
I'm working on a new integration with Amazon Pay and am happy to use whichever SDK / API is best, but have gotten confused about which apis I should be using.

In [this official documentation](https://developer.amazon.com/docs/amazon-pay-onetime/set-and-confirm-purchase.html), it seems to encourage using the OffAmazonPayments MWS apis to call the SetOrderReferenceDetails api. However, from what I've pieced together, that API is an old one and the Checkout v2 API is preferred now as an alternative? Is that the case?

The readme of this project says the following:

> If you need to make an Amazon Pay API call that uses the mws.amazonservices.com|jp or mws-eu.amazonservices.com endpoint, then you will need to use the original Amazon Pay SDK (Node.js).

My presumption is that that old SDK would have support for SetOrderReferenceDetails. However, it links to https://github.com/amzn/amazon-pay-sdk-nodejs, which no longer exists. Is that project now deleted or moved?

My guess here is that the official documentation is just out of date, and that [this new documentation](https://amazonpaycheckoutintegrationguide.s3.amazonaws.com/amazon-pay-api-v2/introduction.html) is what I should be following?

**Comment by bjguillot** [comment]
The original and new APIs have different object models and different front-end interfaces.  A Node.js SDK for the original API was created but never publicly released due to the introduction of the new API.  Both APIs are functional now, but you should avoid mixing-and-matching API operations on an object created from a different API when possible.

In order words, if you use Widgets.js on your front-end pages, then the original API documentation applies (and this SDK does not apply).  If you use the new checkout.js on your front-end pages, then the new documentation and this SDK does apply.

**Comment by joeldenning** [comment]
Thanks for the clarification 👍🏿
